version: '3'

services:
    app:
        image: fofow/dev-environement:latest
        container_name: app
        tty: true
        depends_on:
            - db
        environment:
            DATABASE_URL: postgresql://root:root@127.0.0.1:5432/postgres
        working_dir: /var/www
        volumes:
            - ./:/var/www

    webserver:
        image: nginx:stable
        container_name: webserver
        restart: always
        ports:
            - "8080:80"
        depends_on:
            - app
        volumes:
            - ./:/var/www
            - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - app

    db:
        image: postgres:12
        container_name: db
        restart: always
        volumes:
            - db_data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: root
            POSTGRES_USER: root
            POSTGRES_DB: postgres
        ports:
            - "54320:5432"

#    dbtest:
#        image: postgres:12
#        container_name: dbtest
#        restart: always
#        volumes:
#            - db_data_test:/var/lib/postgresql/data
#        environment:
#            POSTGRES_PASSWORD: root
#            POSTGRES_USER: root
#            POSTGRES_DB: postgres
#        ports:
#            - "54321:5432"

volumes:
    db_data: